const CHANGE_OPEN = "CHANGE_OPEN";
const CHANGE_TO = "CHANGE_TO";
const CHANGE_CC = "CHANGE_CC";
const CHANGE_FROM = "CHANGE_FROM";
const CHANGE_SUBJECT = "CHANGE_SUBJECT";
const CHANGE_TYPE_OF_MAIL = "CHANGE_TYPE_OF_MAIL";
const CHANGE_BODY = "CHANGE_BODY";
const CHANGE_SEND = "CHANGE_SEND";

export { CHANGE_OPEN, CHANGE_TO, CHANGE_CC, CHANGE_FROM, CHANGE_SUBJECT, CHANGE_TYPE_OF_MAIL, CHANGE_BODY, CHANGE_SEND };